#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# montior
xrandr --output HDMI-1 --scale 1.5x1.5 --right-of eDP-1

# daemon
python ~/.config/polybar/launch.py &
nitrogen --restore --force-setter=xinerama &
picom --blur-method dual_kawase --blur-strength 13 &
fcitx5 &
polkit-dumb-agent &
dunst &
dbus-launch --exit-with-session &
redshift -t 5000:3600 -l 33.956215:-83.987861 &

# touchpad
pad=$(xinput list | grep Touchpad | cut -f 2 | cut -d '=' -f 2)
xinput set-prop $pad "libinput Tapping Enabled" 1
xinput set-prop $pad "libinput Natural Scrolling Enabled" 1

# floating rules
bspc config external_rules_command ~/.config/bspwm/scripts/rule.py
