#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# daemon
python ~/.config/polybar/launch.py &
nitrogen --restore --force-setter=xinerama &
picom --blur-method dual_kawase --blur-strength 13 &

# touchpad
pad=$(xinput list | grep Touchpad | cut -f 2 | cut -d '=' -f 2)
xinput set-prop $pad "libinput Tapping Enabled" 1
xinput set-prop $pad "libinput Natural Scrolling Enabled" 1
