[general]
auto_disable = true
init = true
hooks = [
    "nitrogen --restore --force-setter=xinerama",
    "python ~/.config/polybar/launch.py", 
    "xborders --config ~/.config/xborders/config.json"
]
delay = 0.5
hook_delay = 0.5

# ref: https://calculator.academy/dpi-calculator-ppi/
[eDP-1]
xrandr = ["--dpi", "177", "--scale", "1.28x1.28"]
workspaces = ["1"]

[HDMI-1]
xrandr = ["--dpi", "92", "--scale", "1.28x1.28", "--right-of", "eDP-1"]
workspaces = ["2"]
