[general]
auto_disable = true
init = true
hooks = ["python ~/.config/polybar/launch.py", 
         "nitrogen --restore --force-setter=xinerama",
         "picom --backend egl"]
delay = 2

[eDP-1]
xrandr = ["--dpi", "226", "--scale"]
workspaces = ["1"]

[HDMI-1]
xrandr = ["--dpi", "96", "--scale", "1.5x1.5", "--right-of", "eDP-1"]
workspaces = ["2"]
